export default (theme) => {
  return {
    pd: {
      border: "1px solid #DF0000",
      borderRadius: "20px",
      background: "#fff",
      position: "sticky",
      top: "5px",
      overflow: "hidden",
    },
    brands: {
      padding: "4px 8px",
      textAlign: "left",
      lineHeight: 0,
      img: {
        maxHeight: "35px",
        width: "auto",
        maxWidth: "70%",
        height: "auto",
      },
    },
    item: {
      border: "1px solid #ccc",
      borderRadius: "12px",
      background: "#fff",
      position: "relative",
      boxShadow: "0px 0px 4px 0px #aaa",
      "&:hover": {
        boxShadow: "0px 0px 12px 3px #aaa",
        cursor: "pointer",
      },
      height: "100%",
      paddingBottom: "56px",
      transition: "0.2s linear",
    },
    price: {
      background: "#df0000",
      color: "#fff",
      position: "absolute",
      top: "15px",
      right: 0,
      padding: "2px 13px",
      borderTopLeftRadius: "14px",
      borderBottomRightRadius: "14px",
      fontSize: "18px",
      minWidth: "64px",
      textAlign: "center",
      fontWeight: 700,
    },
    offPrice: {
      background: "#00bb13",
      color: "#fff",
      position: "absolute",
      top: "50px",
      right: 0,
      padding: "2px 10px",
      borderTopLeftRadius: "14px",
      borderBottomRightRadius: "14px",
      fontSize: "14px",
      fontWeight: 700,
      minWidth: "64px",
      textAlign: "center",
    },
    image: {
      padding: "4px 0",
      img: {
        maxHeight: "130px",
        width: "auto",
        height: "auto",
        maxWidth: "90%",
      },
    },
    desc: {
      fontSize: "10px",
      textAlign: "left",
      padding: "5px 5px 8px",
      borderTop: "1px solid #ccc",
      fontWeight: 700,
      textAlign: "center",
      margin: "0 5px",
      lineHeight: 1.3,
      wordWrap: "break-word",
    },
    nmBrand: {
      display: "flex",
      margin: "0 10px",
      padding: "4px 0",
      textAlign: "left",
      div: {
        width: "50%",
      },
    },
    brand: {
      color: "#df0000",
      fontSize: "9px",
      fontWeight: 900,
      textAlign: "right",
      paddingRight: "5px",
      a: {
        color: "#df0000",
        "&:hover": {
          textDecoration: "underline",
        },
      },
    },
    nm: {
      fontSize: "12px",
      color: theme.palette.primary.main,
      fontWeight: 600,
    },
    up: {
      background: theme.palette.primary.main,
      padding: "4px 6px",
      color: "#fff",
      borderRadius: "12px",
      fontSize: "22px",
      fontWeight: 600,
      position: "absolute",
      bottom: 0,
      width: "100%",
      lineHeight: 1.3,
    },
    ellipsis: {
      textOverflow: "ellipsis",
      width: "100%",
      overflow: "hidden",
      whiteSpace: "nowrap",
    },
    det: {
      fontSize: "10px",
      a: {
        color: "#fff",
        textDecoration: "underline",
      },
    },
  };
};
